name: Kwiki-VimMode
version: 0.05
abstract: VimMode preformatted forms of text
author: Ian Langworth <ian@cpan.org>
license: perl
distribution_type: module
requires:
  perl: 5.6.1
  Kwiki: 0.30
  Text::VimColor: 0.09
no_index:
  directory:
    - inc
generated_by: Module::Install version 0.39
